In [30]:
import pandas as pd

battery_energy = pd.read_csv('battery_energy.csv')

battery_energy['Date'] = pd.to_datetime(battery_energy['DateTime']).dt.date

new_battery_energy = battery_energy.groupby(['Date','Site']).agg({'battery_current' : 'mean', 'battery_voltage' : 'mean', 'battery_power' : 'mean', 'battery_energy' : 'sum'})

df = pd.to_csv('battery_energy_day.csv')

AttributeError: module 'pandas' has no attribute 'to_csv'

In [14]:
battery_energy['Date'] = pd.to_datetime(battery_energy['DateTime']).dt.date
battery_energy['Date']

0       2022-01-01
1       2022-01-01
2       2022-01-01
3       2022-01-01
4       2022-01-01
           ...
4459    2022-01-31
4460    2022-01-31
4461    2022-01-31
4462    2022-01-31
4463    2022-01-31
Name: Date, Length: 4464, dtype: object

In [28]:
new_battery_energy = battery_energy.groupby(['Date','Site']).agg({'battery_current' : 'mean', 'battery_voltage' : 'mean', 'battery_power' : 'mean', 'battery_energy' : 'sum'})
new_battery_energy

,,battery_current,battery_voltage,battery_power,battery_energy
Date,Site,,,,
2022-01-01,test_site,2.776389,52.270903,3549.835417,794.20
2022-01-02,test_site,2.625000,51.912083,269.190833,786.93
2022-01-03,test_site,5.142657,51.977832,3861.100350,834.10
2022-01-04,test_site,-8.625000,NaN,-294.585417,979.13
2022-01-05,test_site,4.619444,NaN,383.734236,749.59
2022-01-06,test_site,0.647552,52.283611,3381.347902,775.72
2022-01-07,test_site,5.894444,51.851319,3846.468472,829.58
2022-01-08,test_site,-11.905556,51.692639,3671.033125,1007.07
2022-01-09,test_site,8.288889,52.040833,3791.745625,785.80
2022-01-10,test_site,1.515278,52.077639,3595.266806,820.91
2022-01-11,test_site,2.911111,51.835069,3795.737500,854.29
2022-01-12,test_site,-10.276389,51.386181,3693.478194,996.58
2022-01-13,test_site,6.235211,53.233056,3055.268592,627.19
2022-01-14,test_site,2.643056,52.169167,293.950486,786.23
2022-01-15,test_site,1.097902,51.858112,3850.009790,881.80
2022-01-16,test_site,-12.344056,50.279583,3545.177343,991.81
2022-01-17,test_site,4.309722,52.678333,381.803403,707.61
2022-01-18,test_site,2.554167,52.622917,290.818264,759.41
2022-01-19,test_site,NaN,51.761667,NaN,0.00
2022-01-20,test_site,5.525000,52.282238,3569.988819,753.59
2022-01-21,test_site,0.680556,52.201944,3552.138611,804.82
2022-01-22,test_site,-4.323611,52.217986,3517.408194,872.79
2022-01-23,test_site,9.213889,52.531042,3552.300972,713.65
2022-01-24,test_site,-2.566667,NaN,33.713542,889.03
2022-01-25,test_site,-4.379021,52.362292,3709.195035,911.01
2022-01-26,test_site,0.162500,52.489514,3392.677708,786.91
2022-01-27,test_site,6.704167,51.360347,520.276528,779.92
2022-01-28,test_site,-4.998611,51.848819,-90.629653,951.75
2022-01-29,test_site,2.498611,52.312986,285.602083,778.23
2022-01-30,test_site,1.997222,52.395903,257.857708,779.25
2022-01-31,test_site,-0.135664,52.104685,3755.498322,873.35

In [11]:
per_day = battery_energy['DateTime']
per_day

0         1/1/2022 0:00
1         1/1/2022 0:10
2         1/1/2022 0:20
3         1/1/2022 0:30
4         1/1/2022 0:40
             ...
4459    1/31/2022 23:10
4460    1/31/2022 23:20
4461    1/31/2022 23:30
4462    1/31/2022 23:40
4463    1/31/2022 23:50
Name: DateTime, Length: 4464, dtype: object

In [13]:
import datetime
for date in per_day:
    print date.strftime("%d-%m-%Y")

SyntaxError: invalid syntax (747361475.py, line 3)